### ISSUE TITLE
galileo_convertor使用方法

### ISSUE THREAD

**Issue by jieheroli** [JDGalileo/galileo#5]
请问：我安装了galileo的CPU docker，目前执行python3可以进入到环境里面。数据集选择cora的demo也可以跑起来。
可是我们要基于一个大的数据集去做实验，根据github项目提示，我们需要进行数据转换，这就要用到转换工具galileo_convertor。
可是我不知道怎么样才能运行它？各位老师快帮帮弟弟！

**Comment by Hacky-DH** [comment]
@jieheroli 可以参考https://github.com/JDGalileo/galileo/blob/main/docs/data_prepare.md

**Comment by jieheroli** [comment]
![1639036062(1)](https://user-images.githubusercontent.com/10534958/145355236-04b70a81-9154-481d-84ae-5933cd895669.png)
这个文档我详细看了，只介绍了这个工具，但是没说在哪里可以找到。我启动容器后是找不到。

**Comment by Hacky-DH** [comment]
这是因为在CPU的docker容器中工具目录没有加PATH，先执行以下

```
export PATH=/opt/_internal/cpython-3.8.12/bin:$PATH
```

**Comment by jieheroli** [comment]
> 这是因为在CPU的docker容器中工具目录没有加PATH，先执行以下
> 
> ```
> export PATH=/opt/_internal/cpython-3.8.12/bin:$PATH
> ```

**Comment by jieheroli** [comment]
![image](https://user-images.githubusercontent.com/10534958/145366431-8764faac-26bb-4b17-9105-56da58d1ed02.png)
请问下这个报错是什么原因呢

**Comment by jieheroli** [comment]
> 请问下这个报错是什么原因呢

根据报错edge.txt有问题。对比了下vertex.txt和edge.txt后，发现是edge.txt文件格式有问题(结束处多了一个字符)。改正后，执行成功。
